version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=qa


 