app:
  build: .
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:latest
  hostname: localhost  
  environment:
    - MONGO_INITDB_DATABASE=qa
  ports:
    - 27017:27017
 